blog/urls.py
from django.urls import path,include

from    django.conf import  settings
from .  import  views
app_name='blog'
urlpatterns = [
    
    path('',views.blog_all, name='blog_all'),
    path("<int:blog_id>/", views.detail, name="detail")
    

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from    django.conf.urls.static import  static
from    django.conf import  settings
from projectsfolio  import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),

]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField(max_length=300)
    date=models.DateField()

projectsfolio/models.py
from django.db import models
from django.db.models.fields import URLField

class Portfoliomodel(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=300)
    image=models.ImageField(upload_to='projectsfolio/images/')
    url=URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def blog_all(request):
    blog=Blog.objects.all()
    return render(request,'blog/bloghome.html',{'blog':blog})

def detail(request,blog_id):
    blog=get_object_or_404(Blog, pk=blog_id )
    return  render(request, 'blog/detail.html',{'blog':blog})

projectsfolio/views.py
from django.shortcuts import render
from .models import Portfoliomodel

def home(request):
    projects=Portfoliomodel.objects.all()
    return render(request,'projectsfolio/home.html',{'projects':projects})

blog/templates/blog/bloghome.html
{% extends 'projectsfolio/base.html' %}

{% block content %}
<h1>Welcome to Blog!</h1>


<h2>Mohit has written {{blog.count}} blog{{blog.count|pluralize}}</h2>
{% for item in blog%}
<a href="{% url 'blog:detail' item.id  %}">{{item.title}}</a>
<br>
{{item.description|truncatechars:50}}
<br>
{% endfor %}

{%endblock%}

blog/templates/blog/detail.html
{% extends 'projectsfolio/base.html' %}

{% block content %}

{{blog.title}} <br>
{{blog.description}}

{%endblock%}

projectsfolio/templates/projectsfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="icon" type="image/jpg" href="{% static "projectsfolio/logo.jpg" %}">
    <title>Mohit Site!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content  %}{% endblock  %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

projectsfolio/templates/projectsfolio/home.html
{% extends 'projectsfolio/base.html' %}

{% block content %}

    <h1>Welcome</h1>
<h2>test text, this is test for change</h2>

<a href="{% url 'blog:blog_all'%}"> Blog Page</a><br>

{% load static %}
<a href="{% static 'projectsfolio/test.txt'%}">link</a>
<a href="{% static 'projectsfolio/mohittest.pdf'%}"" target="_blank">link</a>

{% for item in projects %}

<h2>{{item.title}}</h2>
<p>{{item.description}}</p>
<img src="{{item.image.url}}" height="400" width="300">
{% if item.url %}<br>
<a href="{{item.url}}">link</a>
{% endif %}

{% endfor %}

{% endblock %}